<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 属性封装 -->
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="radius" value="0.03" />
    <!-- 函数调用 -->
    <myUserPropertyxxx name="${PI}" />
    <myUserPropertyxxx name="${radius}" />
    <!-- 算术运算 -->
    <myUserPropertyYyy name="${PI / 2}" />
    <myUserPropertyYyy name="${radius * 2}" />
</robot>